### PR TITLE
Fix literal funkiness

### LINKED ISSUE #102: Schedule literals behave kinda funky
See https://ethsbell.app/api/v1/schedule, schedule literals are being duplicated a ton

### PR DESCRIPTION
**Pull request by spaghetus**
Closes #102.

Adds a `force_update` endpoint to test refresh behavior in the future, and adds a check when refreshing to ensure that an identical schedule literal does not already exist on a given day.

### CODE REVIEW

**Comment by mswider** [comment]
This is a big improvement, but the schedule still grows each time you do a refresh.
image

I've narrowed this down to 2022-04-13 and 2022-04-14, which still appear to have an identical schedule added on each refresh
image

**Comment by mswider** [comment]
The issue exists because there isn't anything to prevent duplicate entries for partial literal events (added in #96)

**Comment by spaghetus** [comment]
bruh i didn't even remember that we had partial literals

**Comment by spaghetus** [comment]
we should consider changing the calendar data structure to use HashSet in the next version

**Comment by spaghetus** [comment]
ok *now* everything should work correctly

**Comment by spaghetus** [comment]
perhaps it would be better to add explicit deduplication at the end of the update function, idk

**Review by mswider — APPROVED** [review]
Fixed
image

**Pull request merged**
